// Re-export all types from the shared package
// This keeps backward compat with existing imports
export type {
  MarketIndex,
  DataProvenance,
  FieldProvenance,
  Deal,
  Fund,
  SectorMetric,
  NewsCategory,
  Sentiment,
  NewsSignal,
  NewsArticle,
  DealStatus,
  SourcingTarget,
  DealCreateInput,
  CentralBankRate,
  MacroIndicator,
  YieldCurvePoint,
  CreditIndicator,
  MoneyMarketRate,
  MoneyMarketData,
  PortfolioSummary,
  DocumentExtraction,
  ExtractionFlag,
  SourcedTargetMatch,
  TargetPromoteResponse,
  // M&A Engine types (FastAPI :8000)
  SourcedTargetMA,
  SourcedTargetStatus,
  PipelineStage,
  TargetType,
  SourcedTargetListResponse,
  ScanResponse,
  ScanStatus,
  BatchScanResponse,
  // Digital DD (Alt Data)
  TechStackItem,
  TechStackResult,
  SearchTrendPoint,
  SearchTrendsResult,
  DigitalDDReport,
  // Legal & Corporate Watch (Sprint 3)
  MaSignal,
  CorporateEvent,
  LegalEventsReport,
  // Talent & HR Intelligence (Sprint 4)
  TrendSignal,
  JobCategory,
  JobOpening,
  TalentSignalsReport,
  // Portfolio Monitoring (Sprint 6)
  PortfolioCompany,
  PortfolioCompanyListResponse,
  MonthlyKPI,
  MonthlyKPIListResponse,
  // LBO V3 types
  AmortizationType,
  DebtTranche,
  ManagementPackage,
  WaterfallOutput,
  DebtTrancheYear,
  LBOProjectionYear,
  LBOCalculateRequest,
  LBOResult,
  BuildupAddonDetail,
  BuildupRequest,
  BuildupResult,
  BuildupAssumptions,
  // Sector Calibration & LBO Scenarios (D22/D23, Tâche B.8)
  SectorCalibration,
  LBOScenarioCreate,
  LBOScenario,
  LBOScenarioListItem,
  // Trading Comps Engine (Tâche B.10)
  CompSetSummary,
  CompRow,
  CompStats,
  CompStatsBlock,
  CompsTableResponse,
} from '../shared/types';
